[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 1.0
padding = {x = 0, y = 0}
dynamic_padding = true

[font]
normal = {family = "MonaspiceNe Nerd Font Mono", style = "Regular"}
size = 11
builtin_box_drawing = true

[bell]
duration = 0
